### ISSUE TITLE
unrecognized import path "goma"

### ISSUE THREAD

**Issue by IndraGunawan** [hemantasapkota/insta#1]
when i run
`go get .` i got error `package goma: unrecognized import path "goma" (import path does not begin with hostname)`

how to resolve this?

**Comment by hemantasapkota** [comment]
Hi, 

Could you try from master again. I've pushed out a fix.

Thanks

**Comment by IndraGunawan** [comment]
hi @hemantasapkota 
the problem solved,

thanks :)
